### ISSUE TITLE
1.3.1 - Bridge crachs

### ISSUE THREAD

**Issue by tobihoby** [joepool/homebridge-sky-q-no-logs#3]
Hi,

after Update to Version 1.3.1 the brige crashs, if i send the cmd "select" (named: sky ok):

6.3.2021, 21:19:25 [HOOBS 5E10@Sky ok@Sky ok@On] characteristic value expected boolean and received undefined
6.3.2021, 21:19:25 TypeError: switchService.updateCharacteristic(...).getValue is not a function
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-sky-q-no-logs/index.js:92:61)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
6.3.2021, 21:19:25 Got SIGTERM, shutting down Bridge...

Greetings
Tobi

**Comment by joepool** [comment]
Im about to publish version 1.3.2 which will fix these problems.   
the characteristic errors that have been mentioned in issue #1 will be fixed at a later dat

(commit 9818b62)

**Comment by joepool** [comment]
published, please let me know if these issues are fixed. thanks

**Comment by tobihoby** [comment]
it works now, thank you!
