### ISSUE TITLE
No response - Econnrefused

### ISSUE THREAD

**Issue by sterumbelow** [joepool/homebridge-sky-q-no-logs#4]
Hi,

I've suddenly started getting this error m. SkyQ shows as 'No response' in the Home app and doesn't function in Homebridge itself.

I had this one before (back in September) and the only thing that resolved it was changing the IP address.

Any ideas what the issue may be?![image](https://user-images.githubusercontent.com/68124742/110741017-dbeed880-822b-11eb-9217-8f75340281b7.jpeg)

Thanks for your help.

**Comment by joepool** [comment]
Does this happen all the time or only at night? My guess would be only at night which would suggest you have standby mode enabled and set to eco on your Sky Q Box. You can check by going to setting>Setup>Preferences>Standby mode. If it is set to eco then your Sky Q box disables all network connections to it etc between 2:30 and 5:45am. This is why homebridge cannot connect to it and obtain its power state. Setting the Standby mode to none will then fix this problem.

If you are getting this problem at all times of the day, or your box isn't in eco standby mode, let me know and ill see if I can look deeper into the issue.

**Comment by sterumbelow** [comment]
> Does this happen all the time or only at night? My guess would be only at night which would suggest you have standby mode enabled and set to eco on your Sky Q Box. You can check by going to setting>Setup>Preferences>Standby mode. If it is set to eco then your Sky Q box disables all network connections to it etc between 2:30 and 5:45am. This is why homebridge cannot connect to it and obtain its power state. Setting the Standby mode to none will then fix this problem.
> 
> 
> 
> If you are getting this problem at all times of the day, or your box isn't in eco standby mode, let me know and ill see if I can look deeper into the issue. 

Thanks for the response. 

SkyQ box definitely isn't in Eco mode but, having woken up this morning and checked things, I can see the box was stuck in Standby mode and wasn't responding. Restarting it has fixed it.

Sorry for wasting your time!

**Comment by joepool** [comment]
No worries, glad its fixed!
