### ISSUE TITLE
Possible to turn the sky box OFF?

### ISSUE THREAD

**Issue by vadalus911** [joepool/homebridge-sky-q-no-logs#5]
power command does not seem to do this. everything else works great! many thanks

**Comment by joepool** [comment]
what is your config.json for the switch you are trying to use to switch it off?
There should be no issue turning a box off.

**Comment by vadalus911** [comment]
{
            "name": "Sky Q OFF",
            "ipAddress": "10.10.10.213",
            "cmd": "power",
            "accessory": "SkyQ"
        },

**Comment by joepool** [comment]
if you remove the line `"cmd": "power",` this will add a stateful switch to HomeKit that you can use to either turn on or off the sky q box.   
Let me know if that works and is what you're trying to do

**Comment by vadalus911** [comment]
perfect, my bad. i didnt understand the default behaviour is actually what i wanted. working perfectly.
