### ISSUE TITLE
Unable to determine Power state 3

### ISSUE THREAD

**Issue by Jordy15675** [joepool/homebridge-sky-q-no-logs#6]
Hey there,

I'm seeing this error in the HomeBridge logs running build v1.3.2, not sure if this can be fixed or not.

[Sky Q] Unable to determine power state 3
[Sky Q] Perhaps looking at this error will help you figure out whyRequestError: Error: connect EHOSTUNREACH 192.168.0.18:9006

**Comment by joepool** [comment]
this is a typical error that occurs if your sky q box is offline or in eco standby mode which is default during the night.
This could also be caused if the ip address of your sky q box has changed if its dhcp lease has expired.
id check your IP address (Settings>Setup>Network>Advanced Settings>IP address) and standby mode (Settings>Setup>Preferences>Standby mode)

**Comment by Jordy15675** [comment]
Ah yes, for some reason my IP addresses had changed, fixed in the config and all is fine again. I checked the sleep setting and both the Mini and Main Q box are set to active
