### ISSUE TITLE
change icon

### ISSUE THREAD

**Issue by lmarchetello** [joepool/homebridge-sky-q-no-logs#8]
is possible to change the icons of device from classic switch to set top box icon like this: https://cdn.icon-icons.com/icons2/2248/PNG/512/set_top_box_icon_135208.png
thx

**Comment by joepool** [comment]
Afraid not, to have an icon like this the whole plugin would have to be re written as a set top box which just isn't possible at this time. At the moment we are limited by apple and the icons they make available for standard switches.
